### ISSUE TITLE
rowEdit listener werkt niet.. kan knop niet klikken.

### ISSUE THREAD

**Issue by Fusone** [2014-OO3/encoding-farm#11]
![image](https://cloud.githubusercontent.com/assets/9860252/10821702/0cf9bcc4-7e54-11e5-8291-1aee783d09d3.png)

Deze lijn zorgt voor een error in job.xhtml waardoor het "vinkje" bij een rowedit niet kan geklikt worden. Een commit geleden werkte dit nog wel?

**Comment by tmoo3** [comment]
Er was een conflict tussen MySQL en primefaces dateformat.
