### ISSUE TITLE
Hoe gateway aan te spreken vanuit service?

### ISSUE THREAD

**Issue by PieterDr** [2014-OO3/encoding-farm#14]
Ik heb met Elias een nieuwe branch gemaakt (TestEliasPieter) om te experimenteren voor een bericht te kunnen verzenden van het Managerproject naar Workerproject. 

We willen van de JobServiceImpl klasse in manager-domain de JobGatewayImpl in manager-gateway kunnen aanspreken. Momenteel testen we dit door op de job.xhtml pagina van manager-web-async op een knop te drukken die via facade en service een methode in JobGatewayImpl oproept.

Hiervoor hebben we in JobServiceImpl een @EJB JobGateway gezet, maar dit geeft natuurlijk een error aangezien manager-gateway niet gedefinieerd is in de POM van manager-domain. Dit kunnen we ook niet doen aangezien gateway al wel afhangt van domain. 

![image](https://cloud.githubusercontent.com/assets/8881051/11319100/d9fa426a-906b-11e5-9c68-201dae98de58.png)

(op github staat de code die deze fout genereert in JobServiceImpl in commentaar)
Wat is hiervoor de oplossing?

**Comment by luc-steffens-2014** [comment]
Ik kijk verder, maar dit is de fix voor jullie probleem zeer wss :-)
https://github.com/2014-OO3/encoding-farm/commit/7cb637ce03066bccc2c7db98715a8d1da831f11a

**Comment by PieterDr** [comment]
maakt geen verschil op 1e zicht

**Comment by PieterDr** [comment]
Zit hier nog steeds op vast en kan niet voort :confused:

**Comment by luc-steffens-2014** [comment]
Het zal voor morgen zijn.. Hoe is je interview met Gert geweest?

2015-11-26 12:29 GMT+01:00 Pieter Drijkoningen <notifications@github.com>:

**Comment by marnixvanlint** [comment]
Gesprek is zeer goed gegaan :-)
