### ISSUE TITLE
glassfish error

### ISSUE THREAD

**Issue by Fusone** [2014-OO3/encoding-farm#16]
Severe:   Exception while preparing the app : Unable to execute JPA schema generation create command [create table FINISHEDVIDEOS (id varchar(255) not null, CREATED_ON datetime, LAST_UPDATED_ON datetime, V bigint, VideoTitle longtext, uploaded bit, videoDescription longtext, videoPath longtext, primary key (id))]
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "bit" at line 1, column 143.

Ik blijf deze error krijgen bij Glassfish, mijn database is leeg maar op een of ander manier kan hij de table niet aanmaken.

**Comment by luc-steffens-2014** [comment]
Heb je de hibernate dialect gezet in de persistence.xml

**Comment by Fusone** [comment]
Nu krijg ik deze error: 

Severe:   Exception while preparing the app : Unable to resolve name [org.hibernate.dialect.MYSQLDialect] as strategy [org.hibernate.dialect.Dialect]

**Comment by luc-steffens-2014** [comment]
Moet dat niet Mysql5dialect zijn? En het is case sensitive.

**Comment by Fusone** [comment]
Het was een probleem met connectionpool.. Elias heeft het opgelost
