### ISSUE TITLE
sample project starten

### ISSUE THREAD

**Issue by stephandp** [2014-OO3/encoding-farm#2]
[glassfish.txt](https://github.com/2014-OO3/encoding-farm/files/8688/glassfish.txt)

Wanneer ik het sample project wil starten krijg ik in mijn glassfish server verschillende fouten.
Iemand misschien een idee?
Heb een .txt toegevoegd met de log-file van de glassfish server.

**Comment by luc-steffens-2014** [comment]
Kan je de resort uit je application server halen? Want ik heb de indruk dat hij voor de fout zorgt.
Je kan dat op 2 plaatsen doen normaal: 
In netbeans zelf (onder services > servers > glassfish > application ) > rechtklikken en undeploy.
De andere is via de admin-console: localhost:4848  en daar bij applications ergens.

Probeer ook eens op de VM als je de fout kunt reproduceren.
