### ISSUE TITLE
Runnen van de sample applicatie

### ISSUE THREAD

**Issue by Gunther-Van-Kelst** [2014-OO3/encoding-farm#3]
Bij het runnen van de sample applicatie krijg ik volgende fouten:
[glashfish_log.txt](https://github.com/2014-OO3/encoding-farm/files/11226/glashfish_log.txt)

Aangezien deze fout lijkt op degene dat iemand al had gemeld heb ik bij applicaties onder glasfish gaan kijken maar hier staan er geen onder.

Werken met de VM kan ik ook niet omdat ik hier geen internet access op kan verkrijgen en dus niet kan pullen en pushen naar github.

**Comment by PieterDr** [comment]
op site van netbeans kunt ge netbeans + glassfish ineen downloaden.
Ik had gelijkaardige fouten en heb gwn alle projecten (zeker het resortproject) uit netbeans en netbeans zelf verwijderd, dieje installer van netbeans + glassfish gerund en problems are solved. (wel MySQL nog deftig configureren daarna he)

**Comment by luc-steffens-2014** [comment]
Voor de VM zou je even moeten kijken of je firewall the VBox gewoon niet blokt. Ook de netwerksettings in je VM (zou op NAT met externe toegang moeten staan) even controleren.

**Comment by Gunther-Van-Kelst** [comment]
Ik heb de sample lokaal werkende gekregen. Uiteindelijk gewoon alles verwijderd en opnieuw geïnstalleerd, nog wa extra gefoefeld aan vanalles en het werkte ineens.

Voor de VM nog altijd niet werkende gekregen als mensen dezelfde fout zouden hebben. Heb de firewall uitgezet, alle mogelijke Network Adapter settings uitgeprobeerd maar werkt nog altijd niet.
