### ISSUE TITLE
Vraag @ Luc

### ISSUE THREAD

**Issue by PieterDr** [2014-OO3/encoding-farm#4]
Is het de bedoeling dat alle teams een eigen branch aanmaken en daarop werken of mogen we allen op de master werken en committen?

**Comment by luc-steffens-2014** [comment]
Voor jullie gemak zou ik elk applicatie branch maken. We kunnen die altijd achteraf naar master mergen.

Voor de manager zijn er dus 2 teams op dezelfde branch.

Ik zal de merge laten zien in de klas op vrijdag.
