### ISSUE TITLE
Communication error web naar domain

### ISSUE THREAD

**Issue by Gunther-Van-Kelst** [2014-OO3/encoding-farm#5]
Bij het builden van de distributor-web & distributor-domain geeft netbeans de volgende fout:

**Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project encoding-distributor-web: Compilation failure
org/javasmiths/encodingfarm/distributor/web/facade/VideoFacadeImpl.java:[28,29] cannot find symbol
symbol:   method registerVideo(java.lang.String)
location: variable videoService of type org.javasmiths.encodingfarm.distributor.domain.service.VideoService**

commit voor de code:
https://github.com/2014-OO3/encoding-farm/commit/986fd1fc48193508fba3e0b98b3f211971bf30b4

**Comment by luc-steffens-2014** [comment]
Wss is dat omdat je web-laag je domain niet kent. Je kan hem gemakkelijk
aan je dependencies toevoegen door:

Kan je bij dirtibutor-web, op dependency rechts-klikken > Open projects >
{Selecteer het distributor-project} > Druk ok

Dan zou het moeten werken.
Je zou in je pom ook de refentie naar je domain moeten kunnen terug vinden.

Mvg,
Luc

**Comment by Gunther-Van-Kelst** [comment]
Dank u voor het antwoord had het zelf al in orde gekregen maar vraag me niet hoe(paar keer netbeans gesloten, paar keer geleaned en build).

Ik krijg nu een externalcontext resource error van payara dat hij de index.xhtml niet vindt heb dit nochtans correct staan in de web.xml. Enig idee wat er nog deze error kan veroorzaken?
