### ISSUE TITLE
automatische initdb

### ISSUE THREAD

**Issue by PieterDr** [2014-OO3/encoding-farm#6]
Ik heb deze initdb klasse geschreven (in encodingfarm.worker.domain.entity:
@Singleton
@Startup
public class InitDB {
    
    @PersistenceContext()
    private EntityManager em;
    
    @PostConstruct
    public void init() {
        System.out.println("##########################");
        System.out.println("##########################");
        System.out.println("#####Startup Script#######");
        System.out.println("##########################");
        System.out.println("##########################");
        
        List<Object> objectsToSave = new LinkedList<>();
        
        RequestEntity re1 = new RequestEntity();
        re1.setVideo_path("C:/videos/001.mp4");
        objectsToSave.add(re1);
        
        RequestEntity re2 = new RequestEntity();
        re2.setVideo_path("C:/videos/002.mp4");
        objectsToSave.add(re2);
        
        JobEntity je1 = new JobEntity();
        je1.setRequest(re1);
        je1.setStatus("In Progress");
        objectsToSave.add(je1);
        
        JobEntity je2 = new JobEntity();
        je2.setRequest(re2);
        je2.setStatus("In Progress");
        objectsToSave.add(je2);
        
        for(Object o: objectsToSave) {
            em.persist(o);
        }
    }
}

Wanneer ik het encoding-worker-web project opstart krijg ik deze output van Glassfish:
Warning:   Class class InitDB has null package
Info:   ##########################
Info:   ##########################
Info:   #####Startup Script#######
Info:   ##########################
Info:   ##########################
Severe:   Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton InitDB

[stacktrace:](https://github.com/2014-OO3/encoding-farm/files/13359/stacktrace.txt)

**Comment by luc-steffens-2014** [comment]
Dag Pieter,

ik kijk er vanavond naar. Ik kijk laat het jou weten.

Mvg,
Luc

**Comment by PieterDr** [comment]
Het kan zijn dat het misschien iets met mijn lokale configuratie te maken heeft, aangezien ik ondertussen heel wat meer problemen ben tegengekomen.
Ik heb de klasse initdb Wanneer ik worker-web run krijg ik nu deze error:
Severe:   Exception while preparing the app : Could not resolve a persistence unit corresponding to the persistence-context-ref-name [org.javasmiths.encodingfarm.worker.domain.dao.RequestDaoImpl/em] in the scope of the module called [encoding-worker-web]. Please verify your application.
Severe:   Class [ Lorg/javasmiths/encodingfarm/worker/domain/service/RequestService; ] not found. Error while loading [ class org.javasmiths.encodingfarm.worker.web.facade.RequestFacadeImpl ]

**Comment by EliasSerneels** [comment]
Ik had diezelfde error toen ik een nieuwe entity aanmaakte. Toen ik klikte op de @Entity annotatie kreeg ik de optie om een nieuwe persistence.xml aan te maken. Dit heeft toen mijn probleem opgelost. Misschien kan je iets dergelijks proberen?

**Comment by luc-steffens-2014** [comment]
Connectie met de database - Video:

http://somup.com/co6FqmFUQ

**Comment by luc-steffens-2014** [comment]
Ik zie de screencast niet hier bij.

Hier ook de youtube versie
https://youtu.be/8nCKpHv-GzQ
