### ISSUE TITLE
web pages error

### ISSUE THREAD

**Issue by stephandp** [2014-OO3/encoding-farm#7]
Beste

Ik sta bij de keyboard warriors in voor de facade maar zit al enkele dagen vast. 
Ik heb reeds bij enkele andere groepen gehoord maar ook zij weten hier geen antwoord op.

In het project client-web zitten slechts 2 folders
-dependencies
-project files

echter voor de facade toe te voegen heb je naar mijn weten nog steeds een mapje web pages en dergelijke nodig 

Dit alles ontbreekt bij ons.

Misschien is er ets fout gelopen? Of doe ik iets fout.

Hopelijk kan u me helpen

Met vriendelijke groeten
Stephan

antwoord : 

Dag Stephan,

je kijkt naar de project tab. Dit is een vereenvoudigt beeld van de maven-structuur van het project.

Als je naar de files tab gaat zie je dat je een aantal maven-folders ontbreekt. Nl: 
/src/main/java
/src/main/resources
...

Het zou een belletje moeten laten rinkelen. :-)

**Comment by Gunther-Van-Kelst** [comment]
In files alles zelf aanmaken, zien dat je pom goed ligt om de dependencies binnen te halen en dan moet hij normaal de java dependencies en dergelijke zelf aanmaken bij een build.
Om te zien hoe het moet ga is in de files zien van de sample.

**Comment by stephandp** [comment]
ja klopt klopt , het antwoord staat erbij hé Gunter ;)

**Comment by Gunther-Van-Kelst** [comment]
close de issue dan eh
