### ISSUE TITLE
Probleem bij het pushen

### ISSUE THREAD

**Issue by ElliotBraekeleire** [2014-OO3/encoding-farm#8]
Beste,

Wanneer ik probeer te pushen krijg ik deze foutmelding:
![Image](https://cloud.githubusercontent.com/assets/9860216/10540732/fa5cefee-740a-11e5-9c21-5aaacd425656.PNG)

Wanneer ik commit geeft hij geen foutmelding, maar als ik op github ga kijken staan mijn commits er niet tussen.
Weet iemand hoe ik dit kan oplossen?

Mvg, 
Elliot Braekeleire

**Comment by Gunther-Van-Kelst** [comment]
Ik heb hetzelfde probleem. Als ge me de git shell werkt kunde da oplossen.
tutorial me de meest gebruikte git commands=>https://www.ralfebert.de/tutorials/git/

**Comment by luc-steffens-2014** [comment]
Screencast
http://screencast-o-matic.com/watch/co6bbQhndk
